### ISSUE TITLE
参数与显示

### ISSUE THREAD

**Issue by Aixtuz** [byenow/scriptable-widget#1]
感谢开放使用，留几个使用中遇到的细节：
- AQI 请求中 城市名 未使用顶部定义城市；
- 375 宽设备上，天气和年进度会换行；
- [icon] 后跟空格，显示效果更好；

**Comment by byenow** [comment]
> 感谢开放使用，留几个使用中遇到的细节：
> 
> * AQI 请求中 城市名 未使用顶部定义城市；
> * 375 宽设备上，天气和年进度会换行；
> * [icon] 后跟空格，显示效果更好；

感谢反馈，调整右边距为0了，如果还是换行可以尝试修改`renderProgress`中的grid数量，https://github.com/byenow/scriptable-widget/commit/d90fb1dbab89c76e007d31129763cd27b820ee1d
